-- AlterTable
ALTER TABLE `faqs` ADD COLUMN `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `shop` VARCHAR(191) NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NULL,
    MODIFY `question` VARCHAR(191) NULL,
    MODIFY `answer` VARCHAR(191) NULL;
